# Site settings
title: Prudencier | R&D Meets Innovation
email: support@prudencier.com
description: Empowering Gen AI & Spatial Analytics with precision and insight.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.prudencier.com" # the base hostname & protocol for your site
theme: minima # Optional, but we’ll use custom layouts
plugins:
  - jekyll-feed
  - jekyll-seo-tag
twitter_username:
github_username:

# Build settings
markdown: kramdown
